export const CANDIDATE_STATUS = {
  NEW: "NEW",

  AI_PROCESSING: "AI_PROCESSING",
  AI_PROCESSED: "AI_PROCESSED",

  FIRST_CALL_PENDING: "FIRST_CALL_PENDING",
  FIRST_CALL_DONE: "FIRST_CALL_DONE",

  SECOND_CALL_PENDING: "SECOND_CALL_PENDING",
  SECOND_CALL_DONE: "SECOND_CALL_DONE",

  THIRD_CALL_PENDING: "THIRD_CALL_PENDING",
  THIRD_CALL_DONE: "THIRD_CALL_DONE",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",
  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",

  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_REVIEW: "TASK_REVIEW",

  SELECTED: "SELECTED",
  DROPPED: "DROPPED",
};

export const STATUS_VALUES = Object.values(
  CANDIDATE_STATUS
);