export const TIMELINE_EVENTS = {
  RESUME_UPLOADED: "RESUME_UPLOADED",

  AI_PROCESSED: "AI_PROCESSED",

  CANDIDATE_ASSIGNED: "CANDIDATE_ASSIGNED",

  PROFILE_UPDATED: "PROFILE_UPDATED",

  STATUS_CHANGED: "STATUS_CHANGED",

  CALL_LOGGED: "CALL_LOGGED",

  CANDIDATE_LINED_UP: "CANDIDATE_LINED_UP",

  INTERVIEW_SCHEDULED: "INTERVIEW_SCHEDULED",

  INTERVIEW_COMPLETED: "INTERVIEW_COMPLETED",

  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_PASSED: "TASK_PASSED",
  TASK_REWORK_REQUESTED: "TASK_REWORK_REQUESTED",
  TASK_FAILED: "TASK_FAILED",

  EDUCATION_UPDATED: "EDUCATION_UPDATED",
  EXPERIENCE_ADDED: "EXPERIENCE_ADDED",
  EXPERIENCE_UPDATED: "EXPERIENCE_UPDATED",
  EXPERIENCE_DELETED: "EXPERIENCE_DELETED",
  CERTIFICATION_ADDED: "CERTIFICATION_ADDED",
  CERTIFICATION_UPDATED: "CERTIFICATION_UPDATED",
  CERTIFICATION_DELETED: "CERTIFICATION_DELETED",

  SELECTED: "SELECTED",

  DROPPED: "DROPPED",

  INTERVIEW_SELECTED: "INTERVIEW_SELECTED",

  INTERVIEW_TASK_ASSIGNED: "INTERVIEW_TASK_ASSIGNED",

  INTERVIEW_DROPPED: "INTERVIEW_DROPPED",
};